### ISSUE TITLE
TTS0011: TTS Nyamrub Data Formatter for Validation and Contribution Preparation

### ISSUE THREAD

**Issue by jim-gyas** [OpenPecha/tts-nyamrubdata-formatter#1]
### Description: 
Creating a formatter for TTS Nyamrub data tailored for the Nyamrub website in two distinct formats: 
- for validation purposes
- for contribution purposes.

### Completion Criteria:
- Successfully generate validation and contribution datasets with the specified formats and at least 50,000 rows each.
- Ensure all rows in the datasets are tagged with difficulty levels using the TTS Level Tagger

### Resources:
- Nyamrub Data Format : [Nyamrub Format](https://github.com/OpenPecha/nyamrub-backend/tree/main/database)
- TTS Level Tagger : [TTS Level Tagger](https://github.com/OpenPecha/tts-level-tagger)
- STT Level Tagger : [STT Level Tagger](https://github.com/OpenPecha/stt_level_tagger)
- Training Catalog: [Training Catalog](https://docs.google.com/spreadsheets/d/1w837dDD3q-mKD_s7WNhLzCq-gvGtM6wbh6bDwmfR9bU/edit?gid=138265704#gid=138265704)
- Speaker Catalog: [Speaker Catalog](https://docs.google.com/spreadsheets/d/1L9RCHH_Rckz99q1y46lS60alZGAVWT84uBT5xMh4ik4/edit?gid=1281798258#gid=1281798258)

### Validation Format:
```
origin_id,source,target,score,target_dialect,source_language,target_language
1,source_text_13,target audio url 1,10,khampa,tibetan,tibetan
2,source_text_14,target audio url 2,5,U-tsang,tibetan,tibetan
3,source_text_15,target audio url 3,15,Amdo,tibetan,tibetan
```
### Contribution Format:
```
origin_id,source,target,score,target_dialect,source_language,target_language
1,source_text_13,,10,,tibetan,tibetan
2,source_text_14,,5,,tibetan,tibetan
3,source_text_15,,15,,tibetan,tibetan
```

### Subtask:
- [x] Gather all contribution data from the Training Catalog (ensure it contains atleast 50,000 data rows).
- [x] Extract all validation data from the Speaker Catalog (ensure it contains atleast 50,000 data rows), including speakers: Sherab, Nyimatsering, Pematendar, and Tenzinnyidon.
- [x] Develop a script to remove unnecessary columns from the catalog for both contribution and validation data.
- [x] Implement a TTS level tagger to assign difficulty levels to the contribution data based on the syllable count.
- [x] Utilize an STT level tagger to assign difficulty levels to the contribution data based on audio length.
- [x] Create a script to convert the contribution and validation data into their required formats.

#### Reviewer: @gangagyatso4364 
- [x] Reviewed.
